# Generated by Django 4.0.4 on 2022-04-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Semester',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
