# Generated by Django 4.0.4 on 2022-04-21 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0006_project_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='weight',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
