# Generated by Django 4.0.4 on 2022-04-22 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0016_remove_project_teams_team_teams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='teams',
            new_name='projects',
        ),
    ]
