# Generated by Django 4.0.4 on 2022-04-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0017_rename_teams_team_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(to='team_app.team'),
        ),
    ]
