# Generated by Django 4.0.4 on 2022-04-22 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0018_remove_team_projects_project_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, to='team_app.team'),
        ),
    ]
