# Generated by Django 4.0.4 on 2022-04-23 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0020_remove_project_teams_project_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='teams',
        ),
        migrations.AddField(
            model_name='team',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='team_app.project'),
        ),
    ]
