# Generated by Django 4.0.4 on 2022-04-23 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0022_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='criterias',
            field=models.ManyToManyField(to='team_app.criteria'),
        ),
    ]
