# Generated by Django 4.0.4 on 2022-04-24 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0023_project_criterias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='team_app.project')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='team_app.team')),
            ],
        ),
    ]
