# Generated by Django 4.0.4 on 2022-04-24 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0024_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='team_app.project'),
        ),
        migrations.AlterField(
            model_name='report',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='team_app.team'),
        ),
    ]
