# Generated by Django 4.0.4 on 2022-04-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0025_alter_report_project_alter_report_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
