# Generated by Django 4.0.4 on 2022-04-27 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0026_judge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Judge',
        ),
        migrations.AddField(
            model_name='report',
            name='judge',
            field=models.CharField(default='Lailz', max_length=50),
        ),
    ]
